---
title: "Ian's Grad Map Code"
author: "Kate Culhane"
date: "May 29, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load data}

### Load necessary packages ###

library(tidyverse)
library(sp)
library(raster)
library(ggimage)
# library(ggspatial)
select <- dplyr::select

### Load point data ###

peaks_df <- read_csv('peaks.csv')

peaks_xy <- peaks_df %>% 
  select(x, y)

peaks <- SpatialPointsDataFrame(peaks_xy, data = peaks_df,
                                proj4string = CRS('+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'))

peaks_nad <- spTransform(peaks, CRSobj = CRS('+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83
+units=m +no_defs +ellps=GRS80 +towgs84=0,0,0'))

### Load elevation data ###
# NOTE: TIF files are too large to be stored in a git repo and so are housed locally

elevation_us <- raster('../large-files/ian-summit-map/elev48i0100a.tif') # elevation data from https://nationalmap.gov/small_scale/index.html
elevation_crop <- crop(elevation_us, extent(-2130000, -1770000, 2700000, 3180000))
#elevation_simple <- aggregate(elevation_crop, fact = 15)

hillshade_us <- raster('../large-files/ian-summit-map/srgr48i0100a.tif') # hillshade data from https://nationalmap.gov/small_scale/index.html
hillshade_crop <- crop(hillshade_us, extent(-2130000, -1770000, 2700000, 3180000))
#hillshade_simple <- aggregate(hillshade_crop, fact = 15)

```

```{r spatial data frames}

### Coerce spatial files to data frames ###

elevation_df <- as.data.frame(elevation_crop, xy = TRUE) %>% 
  rename(elev = elev48i0100a)
  
hillshade_df <- as.data.frame(hillshade_crop, xy = TRUE) %>%
  rename(shade = srgr48i0100a)

peaks_nad_df <- as.data.frame(peaks_nad, xy = TRUE) %>% 
  select(x.1, y.1, name, type, year, date, elev) %>% 
  rename(x = x.1, y = y.1) %>% 
  mutate(elev = as.numeric(elev))

```

```{r point and legend data frames}

### Wrangle point data for visualization ###

summits <- peaks_nad_df %>% 
  filter(type == 'peak') %>% 
  distinct(name, .keep_all = TRUE) %>% 
  arrange(-elev) %>% 
  mutate(order = as.character(row_number()),
         year = factor(year, levels = c('freshman', 'sophomore', 'junior', 'senior')),
         label = paste0(order, ' - ', name, ' (', elev, ' ft)'),
         labx = c(rep(-1903000, 23), rep(-1861000, 23), rep(-1817000, 23)),
         laby = c(seq(from = 2802000, to = 2722000, length.out = 23), seq(from = 2802000, to = 2722000, length.out = 23), seq(from = 2802000, to = 2722000, length.out = 23)))

other <- peaks_nad_df %>% 
  filter(type != 'peak' & type != 'school') %>% 
  mutate(
    image = case_when(
      type == 'home' ~ './pics/home.png',
      type == 'hiking' ~ './pics/hiking.png',
      type == 'biking' ~ './pics/biking.png',
      type == 'skiing' ~ './pics/skiing.png',
      type == 'climbing' ~ './pics/climbing.png',
      type == 'attempt' ~ './pics/x.png',
      type == 'kayaking' ~ './pics/kayaking.png'
    )
  )

uw <- peaks_nad_df %>% 
  filter(type == 'school') %>% 
  mutate(image = './pics/uwlogo.png')

### Create data frames for legend ###

# Headers
legend_title <- data.frame(x = c(-1846000, -1873000),
                           y = c(2812000, 2839000),
                           label = c('Peaks Summitted, by decreasing elevation', 'Notable Locations and Trips'))

# Summit info text
legend <- data.frame(x = c(seq(-1889000, -1805000, length.out = 4)),
                     y = c(rep(2807000, 4)),
                     label = c('Freshman Year', 'Sophomore Year', 'Junior Year', 'Senior Year'))

# Summit info icons
legend_points <- data.frame(x = c(seq(-1892000, -1808000, length.out = 4)),
                     y = c(rep(2807000, 4)),
                     year = c('freshman', 'sophomore', 'junior', 'senior'))

# Place info text
legend2 <- data.frame(x = c(rep(-1898000, 4), rep(-1861000, 4)),
                      y = c(rep(seq(2834000, 2819000, length.out = 4), 2)),
                      label = c('University of Washington', 'Home - Olympia', 'Hiking or Backpacking', 'Sport Climbing', 'Alpine Skiing', 'Mountain Biking', 'Kayaking', 'Attempted Summit'))

# Place info icons
legend_pics <- data.frame(x = c(rep(-1901000, 4), rep(-1864000, 4)),
                          y = c(rep(seq(2834000, 2819000, length.out = 4), 2)),
                          image = c('./pics/uwlogo.png', './pics/home.png', './pics/hiking.png', './pics/climbing.png', './pics/skiing.png', './pics/biking.png', './pics/kayaking.png', './pics/x.png'))

```

```{r map}

# Create map using ggplot

ggplot() +
  ### MAP ###
 # layer_spatial(elevation_simple) +
 # scale_fill_gradient(low = 'white', high = '#34006B') +
 geom_raster(data = elevation_df,
             aes(x = x, y = y, fill = elev)) +
 scale_fill_gradient(low = 'steelblue4', high = 'white') +
 geom_raster(data = hillshade_df,
             aes(x = x, y = y, alpha = -shade)) +
  ### POINTS ###
  geom_point(data = summits,
             aes(x = x, y = y, color = year),
             shape = 21, stroke = 2, size = 8, fill = '#34006B') + 
  scale_color_manual(values = c('#6f3800', '#bf5f00', '#f29200', '#ffd700')) +
  geom_text(data = summits,
            aes(x = x, y = y, label = order),
            size = 4.5, color = 'white', fontface = 2) +
  geom_image(data = other,
             aes(x = x, y = y, image = image),
             size = 0.01, asp = 0.75, color = '#34006B') +
  geom_image(data = uw,
             aes(x = x, y = y, image = image),
             size = 0.02, asp = 0.75) +
  ### LEGEND ###
 geom_rect(aes(xmin = -1908000, xmax = -1779000, ymin = 2707500, ymax = 2875000),
           fill = 'white', alpha = 0.35) +
  geom_rect(aes(xmin = -1908000, xmax = -1779000, ymin = 2707500, ymax = 2875000),
            fill = NA, color = '#34006B', size = 2) +
 geom_text(aes(x = -1843000, y = 2869000, label = 'STOKE IS HIGH'),
           size = 12, color = 'black', fontface = 2, family = 'serif') +
 geom_text(aes(x = -1843000, y = 2863500, label = 'IAN CULHANE\'S SUMMITS IN WASHINGTON & OREGON, 2015-2019'),
           size = 6.5, color = 'black', fontface = 2, family = 'serif') +
 geom_text(aes(x = -1843000, y = 2852000, label = 'Volcanic peaks, spicy scrambles, gnarly bushwhacks, stormy bails\u2014and everything in between. This map shows most of the notable\nlocations that Ian Culhane visited during his four years as an undergraduate at the University of Washington. This map doesn\'t\nshow the moments behind these visits: ice axes buzzing with electricity during a stormed-out bivvy on Goode Mountain; an entire\ntaco bar and cheesecake hauled up to Three Fingers Lookout; or a glorious Christmas Eve summit of the Mt. Ellinor trailhead, after\nwhich Ian\'s sister drove the family car into a ditch. On this map, these are only coordinates; if you want to know the stories\nbehind the coordinates you\'ll have to ask Ian himself.'),
           size = 4, color = 'black', fontface = 4) +
 geom_text(data = summits,
           aes(x = labx, y = laby, label = label),
           size = 4, color = 'black', hjust = 0, fontface = 2) +
 geom_text(data = legend_title,
           aes(x = x, y = y, label = label),
           size = 7, color = 'black', fontface = 2, family = 'serif') +
 geom_text(data = legend,
           aes(x = x, y = y, label = label),
           size = 5, color = 'black', hjust = 0, fontface = 2) +
 geom_point(data = legend_points,
            aes(x = x, y = y, color = year),
            shape = 21, stroke = 2, size = 8, fill = '#34006B') +
 geom_text(data = legend2,
           aes(x = x, y = y, label = label),
           size = 4.5, color = 'black', hjust = 0, fontface = 2) +
 geom_image(data = legend_pics,
            aes(x = x, y = y, image = image),
            size = 0.01, asp = 0.75, color = '#34006B') +
 geom_image(aes(x = -1901000, y = 2834000, image = './pics/uwlogo.png'),
            size = 0.01, asp = 0.75) +
 geom_text(aes(x = -1782000, y = 2714000, label = 'Map by Kate Culhane, 2019.\nCreated with R; full code at github.com/katekathrynkat/ian-summit-map.\nElevation data from the USGS National Atlas of the United States, Alber\'s projection.\nCongratulations, bud. We\'re all incredibly proud of you. <3'),
           size = 3, color = 'black', hjust = 1, fontface = 4) +
 # annotation_north_arrow(location = 'br', which_north = "true",
 #                        style = north_arrow_fancy_orienteering) +
 # annotation_scale(location = 'br', pad_y = unit(0, 'cm')) +
 geom_segment(aes(x = -1819000, y = 2828000,
                  xend = -1819000+16214, yend = 2828000),
              color = '#34006B', size = 5) +
 geom_segment(aes(x = -1819000+16214, y = 2828000,
                  xend = -1819000+16214+16214, yend = 2828000),
              color = '#ffd700', size = 5) +
 geom_text(aes(x = -1819000, y = 2831000, label = '0'),
            size = 5, color = 'black', fontface = 2) +
  geom_text(aes(x = -1819000+16214, y = 2831000, label = '10'),
            size = 5, color = 'black', fontface = 2) +
  geom_text(aes(x = -1819000+16214+16214+1500, y = 2831000, label = '20 mi.'),
            size = 5, color = 'black', fontface = 2) +
  geom_image(aes(x = -1830000, y = 2828000, image = './pics/rose_14deg.png'),
             size = 0.06, asp = 0.75) +
  ### THEME ###
  theme_void() +
  theme(legend.position = 'none',
        plot.margin = unit(c(0,0,0,0), 'cm'),
        panel.border = element_rect(color = '#34006B', size = 15, fill = NA)) +
  scale_x_continuous(expand = c(0,0,0,0)) +
  scale_y_continuous(expand = c(0,0,0,0)) +
  coord_cartesian()

ggsave('map.pdf', width = 30, height = 40)

# Where to print: https://postersmith.com/

```

